---
title: "Diabetes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Szukseges csomagok es adatok


```{r message=FALSE, warning=FALSE}
library(h2o) # ML
library(lime) # interpretacio
library(mlbench) # adatok
```
<br>
```{r message=FALSE}
data("PimaIndiansDiabetes")
dim(PimaIndiansDiabetes)
```
<br>
```{r message=FALSE}
head(PimaIndiansDiabetes)
```

<br>

##H2O
### Celvaltozo es magyarazovaltozok definialasa

```{r message=FALSE}
target <- "diabetes" 
features <- setdiff(colnames(PimaIndiansDiabetes), target)
print(features)
```

<br>

###  H2O cluster es dataframe
```{r message=FALSE, results="hide"}
h2o.init() #?h2o.init()  max_mem_size, nthreads, ...
h_diabetes <- as.h2o(PimaIndiansDiabetes)
```

<br>

### Tanito- es teszthalmaz letrehozasa
```{r message=FALSE}
n_seed=1234
h_split <- h2o.splitFrame(h_diabetes, ratios = 0.75, seed = n_seed)
h_train <- h_split[[1]] # 75% a modellezeshez
h_test <- h_split[[2]] # 25% a kiertekeleshez
```

<br>

### H2O GBM epetese es kiertekelese

```{r message=FALSE , results="hide" }
model_gbm <- h2o.gbm(x = features,
                     y = target,
                     training_frame = h_train,
                     model_id = "my_gbm",
                     seed = n_seed)
```
```{r message=FALSE}
h2o.performance(model_gbm, newdata = h_test)
```

<br>

### H2O modellek az AutoML segitsegevel

```{r message=FALSE, results="hide"}
model_automl <- h2o.automl(x = features,
                           y = target,
                           training_frame = h_train,
                           nfolds = 5,               # Keresztvalidacio
                           max_runtime_secs = 120,   # Max ido
                           max_models = 100,         # Max modell
                           stopping_metric = "AUC",  # Mire optimalizaljon
                           project_name = "my_automl_d",
                           exclude_algos = NULL,     # Ha ki akarsz zarni valamilyen algoritmust
                           seed = n_seed)
```
```{r message=FALSE}
head(model_automl@leaderboard,10)
```

<br>

```{r message=FALSE}
model_automl@leader
```

<br>

### Kiertekeles: GBM + legjobb AutoML
```{r message=FALSE}
h2o.auc(h2o.performance(model_gbm, newdata = h_test)) 
h2o.auc(h2o.performance(model_automl@leader, newdata = h_test)) 
```

<br>

### Predikcio
```{r message=FALSE, results="hide"}
yhat_test <- h2o.predict(model_automl@leader, h_test)
```
```{r message=FALSE}
h2o.cbind(h_test, yhat_test)
```

<br>

### Modell mentese
```{r message=FALSE}
h2o.saveModel(object = model_automl@leader, 
              path = "./models/",
              force = TRUE)
```

<br>

## LIME
### Magyarazo letrehozasa
```{r message=FALSE}
explainer <- lime::lime(x = as.data.frame(h_train[, features]),
                        model = model_automl@leader)

```

<br>

### Magyarazat
```{r message=FALSE, results="hide"}
d_samp <- as.data.frame(h_test[3, features])  #egy mintat veszunk (a 3-as kicserelheto barmelyik sorra)
row.names(d_samp) <- "Minta 3" 

explanations <- lime::explain(x = d_samp,
                              explainer = explainer,
                              feature_select = "auto",
                              n_labels = 1,    # binaris klasszifikacio - egy osztaly magyarazat
                              n_features = 8) # Top x tulajdonsag
```
```{r message=FALSE}
explanations <- 
  explanations[order(explanations$feature_weight, decreasing = TRUE),]

print(explanations)
```

<br>

### Diagram
```{r message=FALSE}
lime::plot_features(explanations, ncol = 1)
```

<br>

### Masik pelda
```{r message=FALSE, results="hide"}
  d_samp <- as.data.frame(h_test[1, features])
  row.names(d_samp) <- "Minta 1"  
  explanations <- lime::explain(x = d_samp,
                                explainer = explainer,
                                feature_select = "auto",
                                n_labels = 1,   
                                n_features = 8) 
  
  explanations <- 
    explanations[order(explanations$feature_weight, decreasing = TRUE),]
```
```{r message=FALSE}
  print(explanations)
  lime::plot_features(explanations, ncol = 1)
```


<br>

### Hoterkep

```{r message=FALSE, results="hide"}
d_samp <- as.data.frame(h_test[c(1,3), features])
explanations <- lime::explain(x = d_samp,
                              explainer = explainer,
                              feature_select = "auto",
                              n_labels = 1,    
                              n_features = 8) 

```
```{r message=FALSE}
plot_explanations(explanations)
```